name: ai_client
description: "跨平台的AI客户端"

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.0.0
  logger: ^2.5.0
  cupertino_icons: ^1.0.8
  tdesign_flutter: ^0.1.0
  flutter_launcher_icons: ^0.14.3
  easy_localization: ^3.0.7+1
  easy_localization_loader: ^2.0.2
  dio: ^5.8.0+1
  http: ^1.3.0
  flutter_markdown: ^0.7.6+2
  drift: ^2.25.1
  drift_flutter: ^0.2.4
  window_manager: ^0.4.3
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  drift_dev: ^2.25.2
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/windows/sqlite3.dll  # 添加 DLL 到资源声明
    - assets/translations/  # 添加 多语言文件目录 到资源声明
