name: ai_client
description: "跨平台的AI客户端"

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.0.0
  cupertino_icons: ^1.0.8
  tdesign_flutter: ^0.1.0
  flutter_launcher_icons: ^0.14.3
  easy_localization: ^3.0.7+1
  easy_localization_loader: ^2.0.2
  dio: ^5.8.0+1
  http: ^1.3.0
  path: ^1.9.1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.5
  sqflite_common_ffi_web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/windows/sqlite3.dll  # 添加 DLL 到资源声明
    - assets/translations/  # 添加 多语言文件目录 到资源声明
