name: ai_client
description: "AI客户端"

version: 0.0.4
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  drift: ^2.25.1
  drift_flutter: ^0.2.4
  easy_localization: ^3.0.7+1
  easy_localization_loader: ^2.0.2
  flutter_highlighter: ^0.1.1
  flutter_launcher_icons: ^0.14.3
  flutter_markdown: ^0.7.6+2
  flutter_svg: ^2.0.17
  gpt_markdown: ^1.0.16
  http: ^1.3.0
  logger: ^2.5.0
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.0.0
  shared_preferences: ^2.5.3
  window_manager: ^0.4.3
  bot_toast: ^4.1.3
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  drift_dev: ^2.25.2
  flutter_lints: ^5.0.0
  args: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/  # 添加 多语言文件目录 到资源声明
    - assets/assistant/  # 添加 Ai Icon 到资源声明
