# AppId 的值唯一标识此应用。
# 不要在其他应用的安装程序中使用相同的 AppId 值。
app_id: E3A5D45C-F3F7-4305-B3F4-322EC4E9A264
publisher: AiClient
publisher_url: https://github.com/HRET-Dev/AiClient
display_name: AiClient
create_desktop_icon: true